version: "3"

services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: snakedumper
            TZ: Europe/Berlin
        command: "--character-set-server=utf8 --collation-server=utf8_unicode_ci"
        ports:
            - "3306:3306"
